apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-exp-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-exp-controller
subjects:
- kind: ServiceAccount
  name: cicd-exp-controller
  namespace: cicd-exp-system

