apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - config-logging.yaml
  - deployment.yaml
  - namespace.yaml
  - serviceaccount.yaml