/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "cicd-exp-controller/pkg/client/clientset/versioned/scheme"
	context "context"

	apisv1alpha1 "github.com/aws-controllers-k8s/ecr-controller/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RepositoriesGetter has a method to return a RepositoryInterface.
// A group's client should implement this interface.
type RepositoriesGetter interface {
	Repositories(namespace string) RepositoryInterface
}

// RepositoryInterface has methods to work with Repository resources.
type RepositoryInterface interface {
	Create(ctx context.Context, repository *apisv1alpha1.Repository, opts v1.CreateOptions) (*apisv1alpha1.Repository, error)
	Update(ctx context.Context, repository *apisv1alpha1.Repository, opts v1.UpdateOptions) (*apisv1alpha1.Repository, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, repository *apisv1alpha1.Repository, opts v1.UpdateOptions) (*apisv1alpha1.Repository, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.Repository, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.RepositoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.Repository, err error)
	RepositoryExpansion
}

// repositories implements RepositoryInterface
type repositories struct {
	*gentype.ClientWithList[*apisv1alpha1.Repository, *apisv1alpha1.RepositoryList]
}

// newRepositories returns a Repositories
func newRepositories(c *EcrV1alpha1Client, namespace string) *repositories {
	return &repositories{
		gentype.NewClientWithList[*apisv1alpha1.Repository, *apisv1alpha1.RepositoryList](
			"repositories",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1alpha1.Repository { return &apisv1alpha1.Repository{} },
			func() *apisv1alpha1.RepositoryList { return &apisv1alpha1.RepositoryList{} },
		),
	}
}
