apiVersion: v1
kind: Namespace
metadata:
  name: cicd-exp-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-exp-controller
  namespace: cicd-exp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-exp-controller
  template:
    metadata:
      labels:
        app: cicd-exp-controller
    spec:
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: localhost:5001/controller-995e2a980b7b9067a8f11f6cb74f8a43@sha256:8c31baaa029cf46e3e3f9ddd810b69d137517704e5b7892b1030224a24084bcb
          name: controller
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi

---
